if(LLG_STORAGE_TEST_COMPACT)
  foreach(mode IN LISTS compact_modes)
    target_sources(compact_${mode} PRIVATE "${LLG_RT}/value_gmp/net_adapters.c"
      "${LLG_RT}/value_gmp/real_time.c")
    if(NOT MSVC)
      target_link_libraries(compact_${mode} PUBLIC m)
    endif()
    add_executable(compact_${mode}_net_adapters compact_net_adapters.c)
    target_link_libraries(compact_${mode}_net_adapters PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_net_adapters)
    add_test(NAME compact_${mode}_net_adapters COMMAND compact_${mode}_net_adapters)
    set_tests_properties(compact_${mode}_net_adapters PROPERTIES TIMEOUT 180)
    add_executable(compact_${mode}_real_time compact_real_time.c)
    target_link_libraries(compact_${mode}_real_time PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_real_time)
    add_test(NAME compact_${mode}_real_time COMMAND compact_${mode}_real_time)
    foreach(boundary IN ITEMS packed-overflow packed-wide packed-scale real-negative real-nan real-scale real-overflow)
      if(boundary MATCHES "^real-(negative|nan|scale)$")
        set(expected "real delay must be finite and nonnegative")
      else()
        set(expected "delay exceeds the 64-bit tick range")
      endif()
      add_test(NAME compact_${mode}_time_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_real_time>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
    foreach(boundary IN ITEMS strength index range)
      if(boundary STREQUAL "strength")
        set(expected "invalid net drive strength")
      elseif(boundary STREQUAL "index")
        set(expected "invalid net driver index")
      else()
        set(expected "invalid net resolution range")
      endif()
      add_test(NAME compact_${mode}_net_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_net_adapters>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
  endforeach()
endif()
