option(LLG_STORAGE_TEST_COMPACT "Build standalone compact-backend probes" OFF)
set(LLG_GMP_ROOT "" CACHE PATH "Optional GMP installation prefix for compact kernels")
if(LLG_STORAGE_TEST_COMPACT)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(compact_sources "${LLG_RT}/value_gmp/storage.c" "${LLG_RT}/value_gmp/logic.c"
      "${LLG_RT}/value_gmp/arithmetic.c" "${LLG_RT}/value_gmp/kernels.c"
      "${LLG_RT}/value_gmp/selections.c" "${LLG_RT}/value_gmp/references.c"
      "${LLG_RT}/value_gmp/assembly.c")
  add_library(compact_legacy STATIC "${LLG_RT}/llg_value.c")
  target_include_directories(compact_legacy PUBLIC "${LLG_RT}")
  strict_c(compact_legacy)
  if(NOT MSVC)
    target_link_libraries(compact_legacy PUBLIC m)
  endif()
  add_executable(compact_oracle_legacy compact_oracle_bridge.c)
  target_link_libraries(compact_oracle_legacy PRIVATE compact_legacy)
  set_property(TARGET compact_legacy PROPERTY POSITION_INDEPENDENT_CODE ON)
  strict_c(compact_oracle_legacy)
  set(compact_modes portable)
  if(LLG_GMP_ROOT)
    find_path(compact_gmp_include gmp.h PATHS "${LLG_GMP_ROOT}/include" NO_DEFAULT_PATH)
    find_library(compact_gmp_library gmp PATHS "${LLG_GMP_ROOT}/lib" NO_DEFAULT_PATH)
    if(NOT compact_gmp_include OR NOT compact_gmp_library)
      message(FATAL_ERROR "LLG_GMP_ROOT must contain matching include/gmp.h and lib/libgmp")
    endif()
    list(APPEND compact_modes gmp)
  endif()
  foreach(mode IN LISTS compact_modes)
    add_library(compact_${mode} STATIC ${compact_sources})
    target_include_directories(compact_${mode} PUBLIC "${LLG_RT}/value_gmp")
    set_property(TARGET compact_${mode} PROPERTY POSITION_INDEPENDENT_CODE ON)
    if(mode STREQUAL "gmp")
      target_compile_definitions(compact_${mode} PRIVATE LLG_SV4_GMP_KERNELS=1)
      target_include_directories(compact_${mode} PRIVATE "${compact_gmp_include}")
      target_link_libraries(compact_${mode} PUBLIC "${compact_gmp_library}")
    else()
      target_compile_definitions(compact_${mode} PRIVATE LLG_SV4_GMP_KERNELS=0)
    endif()
    strict_c(compact_${mode})
    include("${CMAKE_CURRENT_SOURCE_DIR}/compact_selection.cmake")
    add_executable(compact_${mode}_probe compact_probe.c)
    target_link_libraries(compact_${mode}_probe PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_probe)
    add_test(NAME compact_${mode}_differential COMMAND compact_${mode}_probe)
    set_tests_properties(compact_${mode}_differential PROPERTIES TIMEOUT 180)
    foreach(boundary IN ITEMS limit overflow)
      add_test(NAME compact_${mode}_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_probe>" "-DMODE=${boundary}"
        "-DEXPECTED=width reaches exclusive limit"
        -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
    add_executable(compact_oracle_${mode} compact_oracle_bridge.c)
    target_compile_definitions(compact_oracle_${mode} PRIVATE LLG_ORACLE_COMPACT=1)
    target_link_libraries(compact_oracle_${mode} PRIVATE compact_${mode})
    strict_c(compact_oracle_${mode})
    add_test(NAME compact_${mode}_python_oracle COMMAND "${Python3_EXECUTABLE}"
      "${CMAKE_CURRENT_SOURCE_DIR}/compact_oracle.py"
      "$<TARGET_FILE:compact_oracle_${mode}>" "$<TARGET_FILE:compact_oracle_legacy>")
    set_tests_properties(compact_${mode}_python_oracle PROPERTIES TIMEOUT 180)
    if(UNIX AND NOT APPLE)
      add_executable(compact_${mode}_allocation_probe compact_allocation_probe.c)
      target_link_libraries(compact_${mode}_allocation_probe PRIVATE compact_${mode})
      target_link_options(compact_${mode}_allocation_probe PRIVATE
        -Wl,--wrap=malloc -Wl,--wrap=calloc -Wl,--wrap=realloc)
      strict_c(compact_${mode}_allocation_probe)
      add_test(NAME compact_${mode}_allocations COMMAND compact_${mode}_allocation_probe)
    endif()
    add_executable(compact_${mode}_benchmark compact_benchmark.c)
    target_link_libraries(compact_${mode}_benchmark PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_benchmark)
    add_test(NAME compact_${mode}_benchmark_smoke COMMAND compact_${mode}_benchmark --smoke)
    set_tests_properties(compact_${mode}_benchmark_smoke PROPERTIES TIMEOUT 60)
  endforeach()
endif()
