add_executable(compact_${mode}_consumers_probe compact_consumers_probe.c)
target_link_libraries(compact_${mode}_consumers_probe PRIVATE compact_${mode} compact_legacy)
strict_c(compact_${mode}_consumers_probe)
foreach(case IN ITEMS small wide)
  add_test(NAME compact_${mode}_consumers_${case} COMMAND compact_${mode}_consumers_probe ${case})
  set_tests_properties(compact_${mode}_consumers_${case} PROPERTIES TIMEOUT 180)
endforeach()
add_executable(compact_${mode}_consumers_facade compact_consumers_facade.c)
target_link_libraries(compact_${mode}_consumers_facade PRIVATE compact_${mode})
strict_c(compact_${mode}_consumers_facade)
add_test(NAME compact_${mode}_consumers_facade COMMAND compact_${mode}_consumers_facade)
if(UNIX AND NOT APPLE)
  add_executable(compact_${mode}_consumers_allocations compact_consumers_allocations.c)
  target_link_libraries(compact_${mode}_consumers_allocations PRIVATE compact_${mode})
  target_link_options(compact_${mode}_consumers_allocations PRIVATE
    -Wl,--wrap=malloc -Wl,--wrap=calloc -Wl,--wrap=realloc)
  strict_c(compact_${mode}_consumers_allocations)
  add_test(NAME compact_${mode}_consumers_allocations COMMAND compact_${mode}_consumers_allocations)
endif()
