if(LLG_STORAGE_TEST_COMPACT)
  foreach(mode IN LISTS compact_modes)
    target_sources(compact_${mode} PRIVATE "${LLG_RT}/value_gmp/net_adapters.c")
    if(NOT MSVC)
      target_link_libraries(compact_${mode} PUBLIC m)
    endif()
    add_executable(compact_${mode}_net_adapters compact_net_adapters.c)
    target_link_libraries(compact_${mode}_net_adapters PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_net_adapters)
    add_test(NAME compact_${mode}_net_adapters COMMAND compact_${mode}_net_adapters)
    set_tests_properties(compact_${mode}_net_adapters PROPERTIES TIMEOUT 180)
    foreach(boundary IN ITEMS strength index range)
      if(boundary STREQUAL "strength")
        set(expected "invalid net drive strength")
      elseif(boundary STREQUAL "index")
        set(expected "invalid net driver index")
      else()
        set(expected "invalid net resolution range")
      endif()
      add_test(NAME compact_${mode}_net_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_net_adapters>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
  endforeach()
endif()
