foreach(kind IN ITEMS probe facade benchmark)
  add_executable(compact_${mode}_destinations_${kind} compact_destinations_${kind}.c)
  target_link_libraries(compact_${mode}_destinations_${kind} PRIVATE compact_${mode})
  if(NOT kind STREQUAL "facade")
    target_link_libraries(compact_${mode}_destinations_${kind} PRIVATE compact_legacy)
  endif()
  strict_c(compact_${mode}_destinations_${kind})
endforeach()
foreach(case IN ITEMS exhaustive wide)
  add_test(NAME compact_${mode}_destinations_${case}
    COMMAND compact_${mode}_destinations_probe ${case})
  set_tests_properties(compact_${mode}_destinations_${case} PROPERTIES TIMEOUT 600)
endforeach()
add_test(NAME compact_${mode}_destinations_facade COMMAND compact_${mode}_destinations_facade)
add_test(NAME compact_${mode}_destinations_benchmark_smoke
  COMMAND compact_${mode}_destinations_benchmark --smoke)
if(UNIX AND NOT APPLE)
  add_executable(compact_${mode}_destinations_allocations compact_destinations_allocations.c)
  target_link_libraries(compact_${mode}_destinations_allocations PRIVATE compact_${mode})
  target_link_options(compact_${mode}_destinations_allocations PRIVATE
    -Wl,--wrap=malloc -Wl,--wrap=calloc -Wl,--wrap=realloc)
  strict_c(compact_${mode}_destinations_allocations)
  add_test(NAME compact_${mode}_destinations_allocations COMMAND compact_${mode}_destinations_allocations)
endif()
