if(LLG_STORAGE_TEST_COMPACT)
  add_executable(compact_legacy_facade_adapters compact_facade_adapters.c)
  target_link_libraries(compact_legacy_facade_adapters PRIVATE compact_legacy)
  strict_c(compact_legacy_facade_adapters)
  add_test(NAME compact_legacy_facade_adapters COMMAND compact_legacy_facade_adapters)
  add_executable(compact_adapters_oracle_legacy compact_adapters_oracle_bridge.c)
  target_link_libraries(compact_adapters_oracle_legacy PRIVATE compact_legacy)
  strict_c(compact_adapters_oracle_legacy)
  foreach(mode IN LISTS compact_modes)
    target_sources(compact_${mode} PRIVATE "${LLG_RT}/value_gmp/net_adapters.c"
      "${LLG_RT}/value_gmp/real_time.c"
      "${LLG_RT}/value_gmp/format_index.c")
    if(NOT MSVC)
      target_link_libraries(compact_${mode} PUBLIC m)
    endif()
    add_executable(compact_${mode}_net_adapters compact_net_adapters.c)
    target_link_libraries(compact_${mode}_net_adapters PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_net_adapters)
    add_test(NAME compact_${mode}_net_adapters COMMAND compact_${mode}_net_adapters)
    set_tests_properties(compact_${mode}_net_adapters PROPERTIES TIMEOUT 180)
    add_executable(compact_${mode}_format_index compact_format_index.c)
    target_link_libraries(compact_${mode}_format_index PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_format_index)
    add_test(NAME compact_${mode}_format_index COMMAND compact_${mode}_format_index)
    set_tests_properties(compact_${mode}_format_index PROPERTIES TIMEOUT 180)
    add_executable(compact_${mode}_real_time compact_real_time.c)
    target_link_libraries(compact_${mode}_real_time PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_real_time)
    add_test(NAME compact_${mode}_real_time COMMAND compact_${mode}_real_time)
    foreach(boundary IN ITEMS packed-overflow packed-wide packed-scale real-negative real-nan real-scale real-overflow)
      if(boundary MATCHES "^real-(negative|nan|scale)$")
        set(expected "real delay must be finite and nonnegative")
      else()
        set(expected "delay exceeds the 64-bit tick range")
      endif()
      add_test(NAME compact_${mode}_time_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_real_time>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
    add_executable(compact_${mode}_facade_adapters compact_facade_adapters.c)
    target_compile_definitions(compact_${mode}_facade_adapters PRIVATE LLG_ADAPTER_COMPACT=1)
    target_link_libraries(compact_${mode}_facade_adapters PRIVATE compact_${mode})
    strict_c(compact_${mode}_facade_adapters)
    add_test(NAME compact_${mode}_facade_adapters COMMAND compact_${mode}_facade_adapters)
    foreach(boundary IN ITEMS unknown negative wide limit)
      if(boundary MATCHES "^(unknown|negative)$")
        set(expected "invalid dynamic packed width")
      else()
        set(expected "width reaches exclusive limit")
      endif()
      add_test(NAME compact_${mode}_width_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_facade_adapters>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
    add_executable(compact_adapters_oracle_${mode} compact_adapters_oracle_bridge.c)
    target_compile_definitions(compact_adapters_oracle_${mode} PRIVATE LLG_ADAPTER_COMPACT=1)
    target_link_libraries(compact_adapters_oracle_${mode} PRIVATE compact_${mode})
    strict_c(compact_adapters_oracle_${mode})
    add_test(NAME compact_${mode}_adapters_python_oracle COMMAND "${Python3_EXECUTABLE}"
      "${CMAKE_CURRENT_SOURCE_DIR}/compact_adapters_oracle.py"
      "$<TARGET_FILE:compact_adapters_oracle_${mode}>" "$<TARGET_FILE:compact_adapters_oracle_legacy>")
    set_tests_properties(compact_${mode}_adapters_python_oracle PROPERTIES TIMEOUT 300)
    add_executable(compact_${mode}_adapters_benchmark compact_adapters_benchmark.c)
    target_link_libraries(compact_${mode}_adapters_benchmark PRIVATE compact_${mode} compact_legacy)
    strict_c(compact_${mode}_adapters_benchmark)
    add_test(NAME compact_${mode}_adapters_benchmark_smoke COMMAND compact_${mode}_adapters_benchmark --smoke)
    foreach(boundary IN ITEMS strength index range)
      if(boundary STREQUAL "strength")
        set(expected "invalid net drive strength")
      elseif(boundary STREQUAL "index")
        set(expected "invalid net driver index")
      else()
        set(expected "invalid net resolution range")
      endif()
      add_test(NAME compact_${mode}_net_reject_${boundary} COMMAND "${CMAKE_COMMAND}"
        "-DPROBE=$<TARGET_FILE:compact_${mode}_net_adapters>" "-DMODE=${boundary}"
        "-DEXPECTED=${expected}" -P "${CMAKE_CURRENT_SOURCE_DIR}/expect_failure.cmake")
    endforeach()
  endforeach()
endif()
