file(MAKE_DIRECTORY "${WORK}")
if(COMPILER_ID STREQUAL "MSVC")
  set(flags /std:c11 /I${RT})
  set(output /Fe${WORK}/mixed.exe /Fo${WORK}/model.obj)
  if(MODEL_DEBUG)
    list(APPEND flags /DLLG_CO_DEBUG)
  endif()
  if(ARENA_ONLY)
    list(APPEND flags /DLLG_PROBE_ARENA_ONLY)
  endif()
else()
  set(flags -std=c11 -I${RT})
  set(output -o ${WORK}/mixed)
  if(MODEL_DEBUG)
    list(APPEND flags -DLLG_CO_DEBUG)
  endif()
  if(ARENA_ONLY)
    list(APPEND flags -DLLG_PROBE_ARENA_ONLY)
  endif()
  list(APPEND output -lm)
endif()
execute_process(COMMAND "${COMPILER}" ${flags} "${SOURCE}" "${RUNTIME}" ${output}
  WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE result
  OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
if("${result}" STREQUAL "0" OR "${result}" MATCHES "[Tt]imeout|[Tt]imed out")
  message(FATAL_ERROR "mixed debug modes did not fail to link: ${result}: ${out}${err}")
endif()
string(FIND "${out}${err}" "${EXPECTED}" found)
if(found EQUAL -1)
  message(FATAL_ERROR "wrong mixed-mode failure: ${out}${err}")
endif()
