foreach(mode IN ITEMS tokens enum sparse2009 sparse2001 repeated2009 repeated2001 conversion signed)
  execute_process(COMMAND "${PROBE}" "${mode}" RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "${mode}: exit ${result}\n${output}\n${errors}")
  endif()
  set(expected "")
  if(mode STREQUAL "enum")
    set(expected "llg: memory file `enum.hex`: numeric memory data does not fit the enum base type; load terminated\n")
  elseif(mode STREQUAL "sparse2001")
    set(expected "llg: memory file `sparse.hex`: memory file contains too few words for the selected range\n")
  elseif(mode STREQUAL "repeated2001")
    set(expected "llg: memory file `repeated.hex`: memory file contains more words than the selected range\n")
  elseif(mode STREQUAL "conversion")
    set(expected "llg: memory file `two_state.hex`: X/Z memory data converted to a two-state element\n")
  endif()
  if(NOT output STREQUAL "MEMORY_IMAGE_PASS ${mode}\n" OR NOT errors STREQUAL expected)
    message(FATAL_ERROR "${mode}: unexpected output\n${output}\n${errors}")
  endif()
endforeach()
